openapi: 3.2.0
info:
  title: MapTiler Data API
  version: '1.0'
  description: MapTiler API allows you to programmatically access all the data, maps, services, and resources available in your MapTiler account.
  termsOfService: https://www.maptiler.com/terms/
  contact:
    name: Support
    email: support@maptiler.com
    url: https://docs.maptiler.com/support/requests/
    premium: https://www.maptiler.com/support/
servers:
- description: MapTiler API
  url: https://api.maptiler.com/
security:
- key: []
tags:
- name: Data
paths:
  /data/{dataId}/features.json:
    parameters:
    - $ref: '#/components/parameters/dataId'
    get:
      summary: GeoJSON
      description: GeoJSON containing the vector features.
      tags:
      - Data
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeoJSON'
      operationId: getDataByDataIdFeaturesJson
      x-operation-id-source: derived
components:
  schemas:
    GeoJSON:
      type: object
      externalDocs:
        url: https://tools.ietf.org/html/rfc7946
  parameters:
    dataId:
      name: dataId
      in: path
      description: Identifier of the data. See [MapTiler Datasets](https://cloud.maptiler.com/data/).
      required: true
      schema:
        type: string
  securitySchemes:
    key:
      description: Your own API key from https://cloud.maptiler.com/
      type: apiKey
      name: key
      in: query
